
name: Deploy via FTP

on:
  push:
    branches:
      - main  # Ganti dengan nama branch Anda jika bukan main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Biasanya file ditaruh di folder htdocs pada InfinityFree
          server-dir: ieclop.my.id/htdocs/